#!/usr/bin/env python3
"""
Writes AI-assigned theme tags to themes.csv for all 727 transcripts.
Classifications performed by Claude in-session (no API cost).
Run once to generate the file; re-running is safe (overwrites).
"""

import csv
from pathlib import Path

THEMES_CSV = Path.home() / "TellMeAJoke/content/themes.csv"
NOW = "2026-06-26T17:30:00"

# (filename, themes)
DATA = [
("$ tells blonde joke.mp4","Blonde"),
("1 TonyBackGround (1).mp4","Fails / Bombs"),
("15 year old girl copy.mov","Dirty / Adult, Dark / Morbid"),
("2 Clip1.mp4","Fails / Bombs"),
("2 Clip5.mp4","Fails / Bombs"),
("2 Clip6.mp4","Fails / Bombs"),
("2 black eyes copy-2.mp4","Dirty / Adult, Relationship / Marriage / Dating"),
("2 black eyes copy.mov","Dirty / Adult, Relationship / Marriage / Dating"),
("2 girls screw up badly copy.mov","Fails / Bombs"),
("3 girls in a car copy.mov","Dirty / Adult, Religion"),
("5 cocks copy.mov","Dirty / Adult, Yo Mama"),
("Aaron tells an ethnic jokeR-1.mp4","Race / Ethnic"),
("Adam tells a religious jokeR-1.mp4","Religion"),
("Adam tells ethnic joke 3.mp4","Race / Ethnic"),
("Adrian tells knock knock joke.mp4","Knock Knock"),
("Adrianne tells a chicken joke.mp4","Animals, Fails / Bombs"),
("Airiella phillips with a blonde joke 2.mp4","Blonde, Fails / Bombs"),
("Airmen bill emetts tells lesbian joke.mov","Dirty / Adult"),
("Al tells big toe joke.mp4","Dad Jokes / Puns / Wordplay"),
("Alecia Jr tells Hooters joke.mp4","Dad Jokes / Puns / Wordplay"),
("Alecia tells santa joke.mp4","Dad Jokes / Puns / Wordplay"),
("Alegra tell ethnic joke 4.mov","Race / Ethnic"),
("Alex tells a mafia jokeR.mp4","Dirty / Adult"),
("Alex tells a manly jokeR-1.mp4","Dirty / Adult"),
("Alex tells a tigger jokePG-1.mp4","Dad Jokes / Puns / Wordplay, Animals"),
("Alex tells an ethnic jokeR.mp4","Race / Ethnic, Fails / Bombs"),
("Alex tells an health insurance joke.mp4","Dirty / Adult, Work / Office"),
("Alex tells black joke.mov","Race / Ethnic"),
("Alex tells blonde joke.mov","Blonde"),
("Alice tells m and m joke.mov","Fails / Bombs"),
("Alicia tells a Michael Jackson jokeR-1.mp4","Michael Jackson"),
("Alicia tells an ethnic jokeX.mp4","Race / Ethnic"),
("Alison tells an ethnic joke13.mp4","Race / Ethnic"),
("Allana tells blonde joke 4.mp4","Blonde"),
("Alysa tells priest joke 5.mp4","Religion"),
("Alyssa tells buffalo joke 4.mp4","Dad Jokes / Puns / Wordplay, Animals"),
("Amanda tells turkey joke.mp4","Food, Dad Jokes / Puns / Wordplay"),
("Amy tells tickle test joke.mp4","Dirty / Adult"),
("Andraadge tells deer nuts joke 4.mp4","Dad Jokes / Puns / Wordplay, Food"),
("Andre tells an ethnic joke13.mp4","Race / Ethnic"),
("Andrea tells dog joke 4.mp4","Animals, Dad Jokes / Puns / Wordplay"),
("Andrea tells ethnic joke 4-1.mp4","Race / Ethnic"),
("Andrea tells mickey mouse joke 3.mp4","Dirty / Adult, Relationship / Marriage / Dating, Celebrity / Pop Culture"),
("Andrew tells blonde joke.mov","Blonde"),
("Andria tells knock knock joke.mov","Knock Knock"),
("Andria tells muffin joke 3.mp4","Dad Jokes / Puns / Wordplay"),
("Aneeb tells monkey joke.mp4","Animals, Dad Jokes / Puns / Wordplay"),
("Angel tells bar joke.mp4","Bar / Drinking, Dad Jokes / Puns / Wordplay"),
("Angela tells a chinese joke 3.mov","Race / Ethnic"),
("Angelo tells Harlem joke.mov","Fails / Bombs"),
("Anthony tells an ethic jokeR.mp4","Race / Ethnic"),
("Anthony tells an ethnic jokeR.mp4","Race / Ethnic"),
("Anthony tells christmas tree joke.mp4","Dirty / Adult"),
("Anthony tells wife joke.mp4","Dark / Morbid, Relationship / Marriage / Dating"),
("Anton tells an ethnic jokeR.mp4","Race / Ethnic, Dark / Morbid"),
("Ariel tells an ethnic jokeR.mp4","Race / Ethnic"),
("Army St Gilns tells Navy joke.mp4","Dirty / Adult"),
("Aron tells test tube joke 3.mp4","Dad Jokes / Puns / Wordplay"),
("Ashley tells an orange joke.mp4","Fails / Bombs"),
("Ashley tells blonde joke 3.mp4","Blonde"),
("Ashley tells ethnic jokes 3.mov","Race / Ethnic"),
("Ava tells 2 jokesPG.mp4","Dad Jokes / Puns / Wordplay, Kids Telling Jokes"),
("Ava tells 2 more jokes againPG.mp4","Dad Jokes / Puns / Wordplay, Kids Telling Jokes"),
("Ava tells 2 more jokesPG.mp4","Dad Jokes / Puns / Wordplay, Kids Telling Jokes"),
("Azao tells a mouse jokeR.mp4","Dirty / Adult, Relationship / Marriage / Dating, Celebrity / Pop Culture"),
("Barbara Tells a tomato joke.mp4","Dad Jokes / Puns / Wordplay, Food"),
("Ben tells cow joke 3.mp4","Dad Jokes / Puns / Wordplay, Animals"),
("Ben tells tomato joke 3.mp4","Dad Jokes / Puns / Wordplay, Food"),
("Benjamin tells some funky jokes 4.mp4","Dirty / Adult, Work / Office"),
("Bernie tells an ethnic jokeR.mp4","Race / Ethnic, Dark / Morbid"),
("Bianca tells ghost joke.mov","Dad Jokes / Puns / Wordplay"),
("Big Willy Style tells tampon joke.mp4","Dirty / Adult"),
("Bill Sayers tells a pirate joke.mp4","Dad Jokes / Puns / Wordplay"),
("Bill tells joke about guy with no legs.mp4","Dirty / Adult, Dark / Morbid"),
("Bill tells roses joke.mp4","Fails / Bombs"),
("Billy tells 2 jokes.mp4","Dark / Morbid, Animals"),
("Billy tells a men's room jokeR.mp4","Dirty / Adult"),
("Billy tells an ethnic jokeR.mp4","Race / Ethnic, Dirty / Adult"),
("Blonde tells a blonde joke.mp4","Blonde, Dirty / Adult"),
("Blonde tells a strawberry joke.mp4","Dad Jokes / Puns / Wordplay, Food"),
("Bobby A tells a knock knock jokePG.mp4","Knock Knock"),
("Bobby H tells a witch joke.mp4","Dirty / Adult"),
("Brandon tells a bathroom jokeR.mp4","Fails / Bombs"),
("Brendan tells a Michael Jackson jokeR.mp4","Michael Jackson, Fails / Bombs"),
("Brenden tells stevie wonder joke 3.mp4","Race / Ethnic, Self-Deprecating"),
("Brian dosn't ever get laid!.mp4","Dirty / Adult, Fails / Bombs"),
("Brian tells a dishwasher joke13.mp4","Dirty / Adult, Relationship / Marriage / Dating"),
("Brian tells a savior joke13.mp4","Religion"),
("Brian tells an ethnic jokeR.mp4","Race / Ethnic"),
("Brian tells tasteless joke 4.mp4","Dark / Morbid, Doctor / Medical"),
("Brian tells vagina joke.mp4","Dirty / Adult"),
("Bridgette tells a cow joke.mp4","Animals, Dad Jokes / Puns / Wordplay"),
("Brit tells politician joke.mp4","Political, Dirty / Adult"),
("Brittney tells ethnic joke 3.mov","Race / Ethnic"),
("Brittney tells knock knock joke.mov","Knock Knock"),
("Bronx tells superhero joke 4.mp4","Dirty / Adult, Celebrity / Pop Culture"),
("Bronx tells two jokes 3.mp4","Yo Mama, Blonde, Dirty / Adult"),
("Brooke tells a bunch of jokes and she cute 5.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("Brooke tells a computer joke.mp4","Dirty / Adult"),
("Brooke tells lesbian joke 3.mp4","Dirty / Adult"),
("Caesar tells a finger joke.mp4","Doctor / Medical, Dad Jokes / Puns / Wordplay"),
("Cameron and Chris trade jokesPG.mp4","Race / Ethnic, Animals, Dad Jokes / Puns / Wordplay"),
("Cameron tells a blonde jokePG.mp4","Blonde"),
("Cameron tells a cop jokePG.mp4","Dad Jokes / Puns / Wordplay"),
("Cameron tells a farm jokeR.mp4","Dirty / Adult, Animals"),
("Cameron tells a few jokesR.mp4","Yo Mama, Race / Ethnic, Religion"),
("Cameron tells a hillbilly jokeR.mp4","Dirty / Adult, Relationship / Marriage / Dating"),
("Cameron tells a hillbilly truck jokePG.mp4","Dad Jokes / Puns / Wordplay"),
("Cameron tells a holy jokePG.mp4","Dad Jokes / Puns / Wordplay, Religion"),
("Cameron tells the sheep jokeR.mp4","Dirty / Adult, Animals"),
("Cameron tells yo momma jokesPG.mp4","Yo Mama"),
("Candy man tells yo mamma jokes.mp4","Yo Mama"),
("Carol tells a blonde jokePG.mp4","Blonde"),
("Caroline Clark tells Ethnic Joke.mov","Race / Ethnic"),
("Cash tells a bee joke.mp4","Dad Jokes / Puns / Wordplay, Animals"),
("Cash tells blonde joke.mp4","Blonde"),
("Cassy tells elephant joke.mp4","Animals, Food"),
("Cathy tells a candle joke 3.mp4","Dad Jokes / Puns / Wordplay"),
("Chad tells old waiter joke.mp4","Dirty / Adult, Bar / Drinking"),
("Charming tells cow joke 3.mp4","Animals, Dirty / Adult, Religion"),
("Chase tells two dead baby jokes 4.mp4","Dark / Morbid"),
("Chelsea tells a sandpaper jokePG.mp4","Dad Jokes / Puns / Wordplay"),
("Cheryl humps lefty.mp4","Fails / Bombs"),
("Chicago tells a prostitute joke.mp4","Fails / Bombs"),
("Chris tells 2 baby jokesR.mp4","Dark / Morbid"),
("Chris tells a bodybuilder jokePG.mp4","Dad Jokes / Puns / Wordplay"),
("Chris tells a crazy kangaroo jokeR.mp4","Fails / Bombs, Animals"),
("Chris tells a deadhead jokeR.mp4","Bar / Drinking, Dark / Morbid"),
("Chris tells a marriage jokePG.mp4","Dad Jokes / Puns / Wordplay, Relationship / Marriage / Dating"),
("Chris tells a racist joke 4.mov","Race / Ethnic, Fails / Bombs"),
("Chris tells cow joke 3.mp4","Animals, Dirty / Adult, Food"),
("Chris tells crab joke 4.mp4","Dirty / Adult, Food"),
("Chris tells gyno joke.mp4","Dirty / Adult, Doctor / Medical"),
("Chris walks away.mov","Bar / Drinking, Fails / Bombs"),
("Christian tells a ethnic jokeR.mp4","Race / Ethnic, Dark / Morbid"),
("Christian tells a shipwreck jokeR.mp4","Dark / Morbid, Religion, Lawyer"),
("Christian tells knock knock joke.mp4","Knock Knock, Yo Mama"),
("Christina and Priscilla tell a Michael Jackson jokeR.mp4","Michael Jackson"),
("Christina tells a blonde joke R.mp4","Blonde, Dark / Morbid"),
("Christina tells a snowman jokePG.mp4","Dad Jokes / Puns / Wordplay"),
("Christina tells an ethnic jokeR.mp4","Race / Ethnic, Dad Jokes / Puns / Wordplay"),
("Christina tells blonde joke.mp4","Blonde"),
("Christopher tells recess joke.mp4","Dad Jokes / Puns / Wordplay, Kids Telling Jokes"),
("Chrstina tells knock knock joke 3.mp4","Knock Knock, Dad Jokes / Puns / Wordplay"),
("Chuck tells an artificial jokePG.mp4","Dad Jokes / Puns / Wordplay, Relationship / Marriage / Dating"),
("City guy tells a redneck jokeR.mp4","Race / Ethnic, Fails / Bombs"),
("Claire keeps telling jokes we already heard.mp4","Blonde, Dad Jokes / Puns / Wordplay"),
("Cliff tells a climbing jokePG.mp4","Dad Jokes / Puns / Wordplay"),
("Cola tells teacher joke 1.mp4","Dark / Morbid, Work / Office"),
("Cone tells an alphabet jokePG.mp4","Dad Jokes / Puns / Wordplay"),
("Conner Cook tells elephant joke.mp4","Dad Jokes / Puns / Wordplay, Animals"),
("Corryn tells a sex jokeR.mp4","Dirty / Adult, Relationship / Marriage / Dating"),
("Cory tells a gay joke.mp4","Dirty / Adult"),
("Courtney and Kristen tell great 28 year old joke.mp4","Dirty / Adult"),
("Craig tells an ethnic jokeR.mp4","Race / Ethnic, Food"),
("Craig tells condom joke.mp4","Dirty / Adult"),
("Crystal tells blonde joke 3.mp4","Blonde"),
("Cute chick tells goat joke 4.mp4","Animals, Dark / Morbid"),
("DC tells a beer joke.mp4","Race / Ethnic, Bar / Drinking"),
("Daffy tells knock knock joke 2.mp4","Knock Knock, Fails / Bombs"),
("Damien tells ethnic joke 5.mp4","Race / Ethnic"),
("Dan C tells Michael Jackson jokeR.mp4","Michael Jackson"),
("Dan tells a Michael Jackson jokeR.mp4","Michael Jackson, Fails / Bombs"),
("Dan tells a lame jokePG.mp4","Bar / Drinking, Dad Jokes / Puns / Wordplay"),
("Dan tells an ethnic jokeR.mp4","Race / Ethnic"),
("Dan tells ethnic and religious jokesR.mp4","Race / Ethnic, Religion"),
("Dan tells salesman joke.mp4","Work / Office, Dad Jokes / Puns / Wordplay"),
("Dana tells a Mario joke.mp4","Celebrity / Pop Culture, Dad Jokes / Puns / Wordplay"),
("Dana tells blonde joke.mp4","Blonde, Dirty / Adult"),
("Daniel tells a tampon jokeR.mp4","Dirty / Adult"),
("Daniel tells an ethnic jokeR.mp4","Race / Ethnic"),
("Daryl D tells a Tarzan Joke 4.mp4","Dirty / Adult, Celebrity / Pop Culture"),
("Dave A Tells an Ethnic Joke.mp4","Race / Ethnic"),
("Dave M tells a cowboy jokeR.mp4","Dirty / Adult"),
("Dave tells a bj jokeR.mp4","Dirty / Adult, Dark / Morbid"),
("Dave tells a hampster jokePG.mp4","Fails / Bombs, Animals"),
("Dave tells a wife jokePG.mp4","Relationship / Marriage / Dating"),
("Dave tells blonde joke.mp4","Blonde"),
("David tell ryming joke.mp4","Dad Jokes / Puns / Wordplay, Bar / Drinking"),
("David tells a bunch of lightbulb jokes.mp4","Dad Jokes / Puns / Wordplay, Race / Ethnic"),
("Dean tells 2 jokesR.mp4","Dirty / Adult, Race / Ethnic"),
("Dean tells an old man jokeR.mp4","Old Person Telling a Joke, Dirty / Adult"),
("Derek tells a lesbian jokeR.mp4","Dirty / Adult"),
("Derwin tells a mom n dad joke 3.mp4","Dirty / Adult, Dark / Morbid"),
("Desire tells a number joke.mp4","Dad Jokes / Puns / Wordplay"),
("Diego tells a joke in spanish.mp4","Dirty / Adult, Race / Ethnic"),
("Doc tells an ethnic joke13.mp4","Race / Ethnic"),
("Doc tells vibrator joke 3.mp4","Dirty / Adult"),
("Dogbone tells an ethnic jokeR.mp4","Race / Ethnic"),
("Dollamentry tells a smack joke 2.mp4","Dad Jokes / Puns / Wordplay"),
("Doug tells old lady joke 3.mp4","Dirty / Adult, Dark / Morbid"),
("Doug tells ugly joke 3.mp4","Self-Deprecating"),
("Dr Jackie tells doctor joke 1.mp4","Doctor / Medical, Dad Jokes / Puns / Wordplay"),
("Drunk frank tells black joke-1.mp4","Race / Ethnic"),
("Dunn tells pinochio joke 4.mp4","Dirty / Adult, Celebrity / Pop Culture"),
("Dwayne Tells a Termite Joke.mp4","Animals, Dad Jokes / Puns / Wordplay, Bar / Drinking"),
("Ean tells bird joke.mp4","Animals, Dad Jokes / Puns / Wordplay"),
("Ed tells 1 more ethnic jokeR.mp4","Race / Ethnic"),
("Ed tells a Bill and Monica jokeR.mp4","Political, Celebrity / Pop Culture"),
("Ed tells an ethnic joke13.mp4","Race / Ethnic"),
("Ed tells yet another ethnic jokeR.mp4","Race / Ethnic, Dirty / Adult"),
("Eddie tells a beach jokePG.mp4","Dad Jokes / Puns / Wordplay"),
("Eddie tells a girlfriend joke13.mp4","Dark / Morbid"),
("Eddy tells cheese joke 5.mp4","Dad Jokes / Puns / Wordplay, Food"),
("Eileen tells mothball joke.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("Elizabeth tells a beer joke.mp4","Fails / Bombs"),
("Ellie tells yo momma jokes.mp4","Yo Mama"),
("Eric V and Chris N tell some jokes PG.mp4","Dad Jokes / Puns / Wordplay, Blonde, Animals"),
("Eric V tells a yo momma joke R.mp4","Yo Mama, Dirty / Adult"),
("Eric tell fruedian slip joke.mp4","Dad Jokes / Puns / Wordplay, Relationship / Marriage / Dating"),
("Eric tells an ethnic joke13.mp4","Race / Ethnic"),
("Eric tells frog joke.mp4","Dark / Morbid, Animals"),
("Eric tells whore joke.mp4","Dirty / Adult"),
("Erica tells a bra jokeR.mp4","Race / Ethnic, Dad Jokes / Puns / Wordplay"),
("Erin tells 2 short and 1 long joke.mp4","Fails / Bombs"),
("Erin tells a florida joke .mp4","Fails / Bombs"),
("Erin tells condom joke 4.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("Ernie tells married joke.mp4","Relationship / Marriage / Dating, Self-Deprecating"),
("Erwin tells racial.mov","Race / Ethnic"),
("FRANCES copy.mp4","Dirty / Adult"),
("Felecia tells red sea joke.mp4","Dad Jokes / Puns / Wordplay, Fails / Bombs"),
("Frank tells 85 year old woman dirty joke.mp4","Dirty / Adult, Old Person Telling a Joke"),
("Frank tells an ethnic joke13.mp4","Race / Ethnic"),
("Frank tells mexican joke.mp4","Race / Ethnic, Food"),
("Frank tells polish joke.mp4","Race / Ethnic, Dad Jokes / Puns / Wordplay"),
("Frank tells rabbit joke 3.mp4","Animals, Dark / Morbid"),
("Frank tells rooster joke.mp4","Animals, Dad Jokes / Puns / Wordplay"),
("Frankie_I_MichaelJacksonJokeR.mp4","Michael Jackson"),
("Fred tells a skeleton jokePG.mp4","Dad Jokes / Puns / Wordplay"),
("Freddy tells an anorexic joke 4.mp4","Dark / Morbid, Food"),
("Gabby tells a Michael Jackson jokeR.mp4","Michael Jackson"),
("Gene tells horse joke 3.mp4","Animals, Bar / Drinking"),
("George F tells a bar jokePG.mp4","Animals, Bar / Drinking, Dad Jokes / Puns / Wordplay"),
("George F tells an ethnic jokeR.mp4","Race / Ethnic"),
("George tells a Dad and Son Joke.mp4","Dirty / Adult"),
("George tells retarded guy joke.mp4","Dirty / Adult, Fails / Bombs"),
("German tamponX.mp4","Dirty / Adult, Race / Ethnic"),
("Gilbert tells a snail joke13.mp4","Animals, Bar / Drinking"),
("Gina tells a bikini jokeR.mp4","Self-Deprecating, Dad Jokes / Puns / Wordplay"),
("Girl tells MJ joke 3.mp4","Michael Jackson"),
("Girl tells cow joke 4.mp4","Animals, Food, Dad Jokes / Puns / Wordplay"),
("Girl tells nut joke 2.mp4","Dad Jokes / Puns / Wordplay"),
("Goody tells an david copperfield joke 3.mp4","Dirty / Adult, Celebrity / Pop Culture"),
("Greg and Jimmy tell some ethnic jokesR.mp4","Race / Ethnic"),
("Greg tells a blonde jokeR.mp4","Blonde, Dirty / Adult"),
("Guy in a van tells an ethnic jokeR.mp4","Race / Ethnic"),
("Guy tells a banana jokePG.mp4","Dad Jokes / Puns / Wordplay, Food"),
("Guy tells a gay jokeR.mp4","Dirty / Adult"),
("Guy tells an Alzheimers jokePG.mp4","Dad Jokes / Puns / Wordplay, Doctor / Medical"),
("Guy tells an ethnic jokeR.mp4","Race / Ethnic"),
("Harold tells catholic joke.mp4","Religion"),
("Harris tells a chauvinist jokeR.mp4","Dirty / Adult, Relationship / Marriage / Dating"),
("Harry Shantz tells a bunch of jokes.mp4","Dad Jokes / Puns / Wordplay"),
("Harry snaps on Davey.mp4","Fails / Bombs"),
("Harvey Sr.mp4","Dirty / Adult, Animals"),
("Heather Allison tells MJ joke.mp4","Michael Jackson, Knock Knock"),
("Hot Enza has ichy butt.mp4","Dirty / Adult"),
("Howard and Samantha tell monkey joke.mov","Animals, Dark / Morbid"),
("Ina tells penguin joke.mp4","Animals, Dad Jokes / Puns / Wordplay"),
("Isabella tells a Polish Joke.mp4","Race / Ethnic"),
("Ishmail tells black jokes.mp4","Race / Ethnic, Dark / Morbid"),
("JR tells mexican joke.mp4","Race / Ethnic"),
("Jack tells a lesbian jokeR.mp4","Dirty / Adult"),
("Jack tells a woman jokePG.mp4","Dirty / Adult, Relationship / Marriage / Dating"),
("Jack tells european joke.mp4","Dad Jokes / Puns / Wordplay"),
("Jackie tells knock knock.mp4","Knock Knock, Dad Jokes / Puns / Wordplay"),
("Jacob tells horrible joke.mp4","Bar / Drinking, Dad Jokes / Puns / Wordplay"),
("James tells a love joke.mp4","Dirty / Adult, Relationship / Marriage / Dating"),
("James tells antenna joke.mp4","Relationship / Marriage / Dating, Dad Jokes / Puns / Wordplay"),
("James tells ethnic joke 5.mp4","Race / Ethnic"),
("Jane tells single joke 5.mp4","Self-Deprecating"),
("Janet tells an ethnic jokeR.mp4","Race / Ethnic, Dad Jokes / Puns / Wordplay"),
("Jaquilyn tells husband joke 4.mp4","Relationship / Marriage / Dating, Dad Jokes / Puns / Wordplay"),
("Jarod tells an ethnic jokeR.mp4","Race / Ethnic"),
("Jarrod tells police man joke.mp4","Dad Jokes / Puns / Wordplay"),
("Jason apologizez for bad joke.mp4","Animals, Fails / Bombs"),
("Jay B tells dirty joke.mp4","Dirty / Adult, Work / Office"),
("Jay tells funny rooster joke.mp4","Animals, Dirty / Adult, Old Person Telling a Joke"),
("Jeff and Sue tell ethnic joke 2.mp4","Race / Ethnic"),
("Jeff gets pissed and walks offR.mp4","Fails / Bombs"),
("Jeff starts an ethnic jokeR.mp4","Race / Ethnic, Fails / Bombs"),
("Jeff tells a cannibal jokePG.mp4","Dark / Morbid, Food"),
("Jeffery tells MJ joke.mp4","Michael Jackson"),
("Jennifer tells bra jke 4.mp4","Dad Jokes / Puns / Wordplay"),
("Jennifer tells ihop joke 3.mp4","Dad Jokes / Puns / Wordplay"),
("Jenny tells shark joke.mp4","Animals, Dad Jokes / Puns / Wordplay"),
("Jenny tells turkey joke.mp4","Food, Dad Jokes / Puns / Wordplay"),
("Jeremy tells a hippie joke13.mp4","Dark / Morbid, Dad Jokes / Puns / Wordplay"),
("Jeremy tells two ethnic jokesR.mp4","Race / Ethnic, Dad Jokes / Puns / Wordplay"),
("Jerry tells a driving jokeR.mp4","Fails / Bombs, Dark / Morbid"),
("Jerry tells blonde joke.mp4","Blonde"),
("Jesse tells fat joke 3.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("Jessica tells a Snoop jokePG.mp4","Celebrity / Pop Culture, Dad Jokes / Puns / Wordplay"),
("Jessica tells a blonde jokeR.mp4","Fails / Bombs, Blonde"),
("Jessica tells a sporty jokePG.mp4","Sports, Dad Jokes / Puns / Wordplay"),
("Jessica tells gay cop joke.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("Jill tells an ethnic joke13.mp4","Race / Ethnic"),
("Jim Kapinsky tells wife joke.mp4","Relationship / Marriage / Dating, Food"),
("Jimmy tellls some jokesR.mp4","Race / Ethnic, Dark / Morbid"),
("Jimmy tells a baby jokeR.mp4","Dark / Morbid"),
("Jimmy tells dirty joke 2.mp4","Dirty / Adult"),
("Joanna tells Clinton joke.mov","Political, Celebrity / Pop Culture"),
("Joe at the Gap tells an ethnic jokeR.mp4","Race / Ethnic"),
("Joe tells a Christopher Reeves jokePG.mp4","Celebrity / Pop Culture, Dad Jokes / Puns / Wordplay"),
("Joe tells a black and blue jokeR.mp4","Dirty / Adult"),
("Joe tells a golf jokePG.mp4","Sports, Dad Jokes / Puns / Wordplay"),
("Joe tells a knock knock jokePG.mp4","Knock Knock"),
("Joe tells an Afghanistan jokePG.mp4","Political, Dad Jokes / Puns / Wordplay"),
("Joe tells an Ellen jokeR.mp4","Celebrity / Pop Culture, Dirty / Adult"),
("Joe tells old lady joke.mp4","Old Person Telling a Joke"),
("Joeseph tells yo momma joke.mp4","Yo Mama, Fails / Bombs"),
("Joey tells a Princess Di jokeR.mp4","Celebrity / Pop Culture, Dirty / Adult, Dark / Morbid"),
("Joey tells a bathroom jokeR.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("John Castolano tells canadian joke.mp4","Dirty / Adult, Sports"),
("John H tells a Pope jokePG.mp4","Religion, Celebrity / Pop Culture"),
("John Lucca tells ADD joke.mp4","Doctor / Medical, Dad Jokes / Puns / Wordplay"),
("John M tells no arms no legs jokes13.mp4","Dad Jokes / Puns / Wordplay"),
("John Power tells 3 MJ jokes.mp4","Michael Jackson, Knock Knock"),
("John tells Italian navy joke.mp4","Race / Ethnic"),
("John tells MJ joke.mp4","Michael Jackson, Blonde"),
("John tells a Santa jokeR.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("John tells a confessional jokeT.mp4","Religion, Dirty / Adult"),
("John tells a cow jokePG.mp4","Animals, Fails / Bombs"),
("John tells a genie jokeR.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("John tells a nasty hookup jokeR.mp4","Old Person Telling a Joke, Dirty / Adult, Dark / Morbid"),
("John tells a nuts joke.mp4","Dirty / Adult, Fails / Bombs"),
("John tells a polar bear jokePG.mp4","Animals, Bar / Drinking, Dad Jokes / Puns / Wordplay"),
("John tells an alligator joke.mp4","Dirty / Adult, Animals, Race / Ethnic"),
("John_S_Leperjoke_PG.mp4","Dark / Morbid, Bar / Drinking"),
("Johnny Salami tells a bunch of jokes.mp4","Dirty / Adult, Religion, Race / Ethnic"),
("Johnny Salami tells an ethnic jokeR.mp4","Race / Ethnic"),
("Johnny and davey tell two jokes.mp4","Blonde, Race / Ethnic"),
("Joint man telling a hoe joke .mp4","Dirty / Adult"),
("Jose tells a sex jokeR.mp4","Dark / Morbid, Dirty / Adult"),
("Josh tells an animal jokeR.mp4","Animals, Bar / Drinking, Dad Jokes / Puns / Wordplay"),
("Joshua tells mom joke 3.mp4","Yo Mama, Dark / Morbid"),
("Joshua tells quarterback joke.mp4","Sports, Dad Jokes / Puns / Wordplay"),
("Julia tells santa joke.mp4","Fails / Bombs"),
("Julie Ann tells fan joke.mp4","Sports, Dad Jokes / Puns / Wordplay"),
("Justice tells two ethnic jokes 4.mp4","Race / Ethnic, Dark / Morbid"),
("Justin tells helen keller joke 4.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("Kate tells fuck joke 5.mp4","Dirty / Adult, Fails / Bombs"),
("Katelyn tells classic mushroom joke 3.mp4","Dad Jokes / Puns / Wordplay"),
("Keith shinsha tells monica lewinsky joke.mp4","Political, Celebrity / Pop Culture"),
("Keith tells an ethnic jokeR.mp4","Race / Ethnic, Dark / Morbid"),
("Kelly Power tissue joke.mp4","Dad Jokes / Puns / Wordplay"),
("Kelly and Bridget tell racist joke.mp4","Race / Ethnic, Dark / Morbid"),
("Kelly tells 2 black jokes.mp4","Race / Ethnic, Dark / Morbid"),
("Kelly tells quick blonde joke.mp4","Blonde"),
("Kelvin Tells a Jesus Joke.mp4","Religion"),
("Ken tells a togetherness jokeR.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("Kenny gets cut off by guy telling ethnic joke.mp4","Race / Ethnic, Fails / Bombs"),
("Kenny tells a religious jokeR.mp4","Religion, Dirty / Adult"),
("Kenny tells an ethnic joke13.mp4","Race / Ethnic"),
("Kenny tells gay joke 3.mp4","Dirty / Adult"),
("Kev and Jeffery tell black guy jokes.mp4","Race / Ethnic, Dark / Morbid"),
("Kev and Paul tell your mama jokes plus one racist.mp4","Yo Mama, Race / Ethnic"),
("Keven W tells TP joke.mp4","Dad Jokes / Puns / Wordplay"),
("Kevin jumps a dude R.mp4","Fails / Bombs"),
("Kevin tells 2 dirty jokes.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("Kevin tells an ethnic joke13.mp4","Race / Ethnic"),
("Kevin tells an ethnic jokeR.mp4","Race / Ethnic"),
("Kevin tells black kid joke.mp4","Race / Ethnic"),
("Kevin tells penis joke.mp4","Doctor / Medical, Dad Jokes / Puns / Wordplay"),
("Kid tells pee joke.mp4","Kids Telling Jokes, Dad Jokes / Puns / Wordplay"),
("Kiki tells a toy box jokeR.mp4","Dirty / Adult"),
("Kristen tells a blonde joke R.mp4","Blonde"),
("Kristen tells a fat joke-top joke!13.mp4","Relationship / Marriage / Dating, Dirty / Adult"),
("Kristen tells a gay dino joke13.mp4","Dirty / Adult"),
("Kristen tells a handy jokeR.mp4","Dad Jokes / Puns / Wordplay"),
("Kristen tells a rabbit sex joke13.mp4","Fails / Bombs"),
("Kristina tells a dishwasher jokePG.mp4","Relationship / Marriage / Dating, Dad Jokes / Puns / Wordplay"),
("Kristina tells a nun joke LONG.mp4","Dirty / Adult, Religion"),
("Kyle is an asshole.mp4","Dad Jokes / Puns / Wordplay"),
("Lacey tells a fat joke 3.mp4","Self-Deprecating, Dad Jokes / Puns / Wordplay"),
("Lady tells stupid joke 3.mp4","Animals, Fails / Bombs"),
("Lauren and Lydia tell 2 jokesPG.mp4","Celebrity / Pop Culture, Knock Knock, Dad Jokes / Puns / Wordplay"),
("Lauren tells a fighter pilot joke 5.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("Lauren tells dog joke g.mp4","Animals, Dad Jokes / Puns / Wordplay"),
("Lauren tells talkin muffin joke.mp4","Dad Jokes / Puns / Wordplay, Food"),
("Lefty tells black joke.mp4","Race / Ethnic, Dirty / Adult"),
("Lefty tells stork joke.mp4","Dirty / Adult, Race / Ethnic"),
("Lenny tells a husband joke.mp4","Relationship / Marriage / Dating, Dark / Morbid"),
("Leslie tells an ethnic jokeR.mp4","Race / Ethnic"),
("Lewis tells cuban joke.mp4","Religion, Fails / Bombs"),
("Lily tells a yo momma jokePG.mp4","Yo Mama"),
("Linda tells a blonde joke 2.mp4","Blonde, Dad Jokes / Puns / Wordplay"),
("Lindsey and lauren tell yo mamma joke 3.mp4","Yo Mama"),
("Liz tells a Bill and Monica jokeR.mp4","Political, Celebrity / Pop Culture"),
("Lori tells a pirate jokePG.mp4","Dad Jokes / Puns / Wordplay"),
("Lorraine tells a divorce joke13.mp4","Relationship / Marriage / Dating"),
("Lorrainne tells yo mamma joke 3.mp4","Yo Mama"),
("Lucas tells blonde joke 4.mp4","Blonde"),
("Lucas tells god joke 3.mp4","Race / Ethnic, Fails / Bombs"),
("Lucy tells HMO joke 3.mp4","Doctor / Medical, Religion"),
("Manuel tells a bird joke 4.mp4","Work / Office, Dad Jokes / Puns / Wordplay"),
("Marc tells a sex jokeRtopjoke.mp4","Dirty / Adult, Relationship / Marriage / Dating"),
("Marco tells 2 ethnic jokesR.mp4","Race / Ethnic"),
("Marco tells a pizza delivery jokeR.mp4","Dirty / Adult, Food"),
("Marco tells joke in german .mp4","Animals, Dad Jokes / Puns / Wordplay"),
("Margo and john tell black joke.mp4","Race / Ethnic, Sports"),
("Margo tells black joke and she is hot.mp4","Race / Ethnic"),
("Maria and Vanessa tell ethnic joke 5.mp4","Race / Ethnic, Fails / Bombs"),
("Maria tells an ethnic jokeX.mp4","Race / Ethnic"),
("Marie tells a bank joke 3.mp4","Dad Jokes / Puns / Wordplay"),
("Marina tells a 50 cent joke.mp4","Celebrity / Pop Culture, Fails / Bombs"),
("Marisa tells an ethnic joke13.mp4","Race / Ethnic"),
("Mark is retarded 1.mp4","Animals, Dad Jokes / Puns / Wordplay"),
("Mark tells a drummer jokePG.mp4","Sports, Dad Jokes / Puns / Wordplay"),
("Mark tells an ethnic literature joke13.mp4","Race / Ethnic"),
("Mark tells ethnic joke 5.mp4","Race / Ethnic, Dirty / Adult"),
("Mark tells honeymoon joke 4.mp4","Dirty / Adult, Relationship / Marriage / Dating"),
("Mark tells lesbian frog joke.mp4","Dirty / Adult, Animals"),
("Mark tells two jokes 2.mp4","Dad Jokes / Puns / Wordplay, Food"),
("Marlo fells MJ joke 4.mp4","Michael Jackson"),
("Marrisa tells naked dwarf joke.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("Marta tells intellectual joke.mp4","Bar / Drinking, Dad Jokes / Puns / Wordplay"),
("Mary tells dirty joke 3.mp4","Animals, Dark / Morbid"),
("Mary tells monkey joke.mp4","Animals, Dark / Morbid"),
("Mary tells southern joke.mp4","Dirty / Adult, Relationship / Marriage / Dating"),
("Matt B hell joke.mp4","Religion, Dirty / Adult"),
("Matt M tells an animal joke PG.mp4","Animals, Dad Jokes / Puns / Wordplay, Food"),
("Matt tells a wife jokeR_topjoke.mp4","Dirty / Adult, Relationship / Marriage / Dating"),
("Matt tells an ethnic jokeR.mp4","Race / Ethnic, Dirty / Adult"),
("Matt_S_EthnicJokeR.mp4","Race / Ethnic, Dark / Morbid"),
("Meg and Elise tell a potato jokeR.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("Meg and Elise tell a radio contest jokePG.mp4","Dad Jokes / Puns / Wordplay"),
("Meg tells a shoelace jokePG.mp4","Race / Ethnic, Dad Jokes / Puns / Wordplay"),
("Meghan tells a cuban joke.mp4","Race / Ethnic"),
("Meghan tells an ADD joke.mp4","Doctor / Medical, Dad Jokes / Puns / Wordplay"),
("Mel tells two cute jokes 5.mp4","Dad Jokes / Puns / Wordplay, Animals"),
("Melinda tells blonde joke 5.mp4","Dirty / Adult, Race / Ethnic"),
("Merdock tells penis joke 4.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("Merv ellis tells cow joke.mp4","Animals, Food, Dad Jokes / Puns / Wordplay"),
("Michael tells a leper joke13.mp4","Dark / Morbid, Bar / Drinking"),
("Michael tells a santa joke 2.mp4","Dirty / Adult"),
("Michelle Micklight tells blonde joke.mp4","Blonde, Dirty / Adult"),
("Michelle tells a dog joke.mp4","Animals, Dirty / Adult"),
("Michelle tells religous joke 4.mp4","Dirty / Adult, Religion"),
("Michelle tells two blonde jokes 4.mp4","Blonde, Dirty / Adult"),
("Mike Downs tells Jesus joke.mp4","Religion"),
("Mike G tells 2 jokesR.mp4","Kids Telling Jokes, Knock Knock, Dirty / Adult"),
("Mike O religious JokerR.mp4","Religion, Race / Ethnic, Bar / Drinking"),
("Mike O tells a lab rabbit joke13_topjoke.mp4","Animals, Dirty / Adult"),
("Mike O tells a marriage jokeR.mp4","Dirty / Adult, Relationship / Marriage / Dating"),
("Mike O tells an afterlife jokeR.mp4","Race / Ethnic, Dirty / Adult"),
("Mike R tells an ethnic joke.mp4","Race / Ethnic"),
("Mike tells MJ joke 2.mp4","Michael Jackson"),
("Mike tells a Helen Keller jokeR.mp4","Dad Jokes / Puns / Wordplay"),
("Mike tells a NY Jets jokePG_topjokes.mp4","Sports, Dad Jokes / Puns / Wordplay"),
("Mike tells a blonde jokePG.mp4","Blonde"),
("Mike tells a cannibal jokePG.mp4","Dark / Morbid, Food"),
("Mike tells aids joke 3.mp4","Dark / Morbid, Dirty / Adult"),
("Mike tells an anorexic jokeR.mp4","Dark / Morbid, Food"),
("Mike tells lesbian dinosaur joke.mp4","Dirty / Adult"),
("Mike tells santa jokes.mp4","Dad Jokes / Puns / Wordplay"),
("Mikey tells politically correct jokr.mp4","Race / Ethnic, Fails / Bombs"),
("Mitch steals my talking sausage joke.mp4","Dad Jokes / Puns / Wordplay, Food"),
("Molly tells blonde joke 3.mp4","Blonde"),
("Monica tells dirty joke 2.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("Monica tells tog joke 3.mp4","Animals, Dad Jokes / Puns / Wordplay"),
("Myada tells arbees joke 3.mp4","Dad Jokes / Puns / Wordplay, Food"),
("NY girl tells ethnic joke 5.mp4","Race / Ethnic, Relationship / Marriage / Dating"),
("Nata tells a period jokeR.mp4","Dirty / Adult"),
("Natalie tells number joke.mp4","Dad Jokes / Puns / Wordplay"),
("Nate tells ethnic joke 5.mp4","Race / Ethnic"),
("Needa tells ethnic joke 3.mp4","Race / Ethnic"),
("Neely tells archeologist joke.mp4","Dad Jokes / Puns / Wordplay, Work / Office"),
("Nelson tells the long faced horse joke -1.mp4","Animals, Bar / Drinking"),
("Nick B tells a ghost jokeR.mp4","Religion, Dirty / Adult"),
("Nick brick joke LONG.mov","Dad Jokes / Puns / Wordplay, Animals"),
("Nick hurts himselfR.mp4","Fails / Bombs"),
("Nick lays Joe outR.mp4","Fails / Bombs"),
("Nick tells 2 helen keller jokes 4.mp4","Dirty / Adult, Dark / Morbid"),
("Nick tells Polish jokes.mp4","Race / Ethnic, Fails / Bombs"),
("Nick tells an ethnic jokeX.mp4","Race / Ethnic, Fails / Bombs"),
("Nick tells family tree joke.mp4","Race / Ethnic, Dark / Morbid"),
("Nicky bang bang tells a bj jokeR_topjoke.mp4","Dirty / Adult"),
("Nicole tells a blonde jokeX.mp4","Blonde, Fails / Bombs"),
("Nicole tells a snoop dogg joke.mp4","Celebrity / Pop Culture, Fails / Bombs"),
("Nicolette Bianca and Stephanie tell a woman jokeR.mp4","Dirty / Adult"),
("Nicolette and Brianne tell a blonde jokeR.mp4","Blonde, Dirty / Adult"),
("Nina and Danielle tell a blonde jokeR.mp4","Blonde, Dirty / Adult"),
("Noelle tells mickey joke 2 .mp4","Fails / Bombs"),
("Norm tells a blonde jokeR.mp4","Blonde, Fails / Bombs"),
("Norm tells a condom jokeR.mp4","Dirty / Adult"),
("Norm tells an ethnic jokeR.mp4","Race / Ethnic, Dark / Morbid"),
("Old Guy forgets joke.mp4","Old Person Telling a Joke, Fails / Bombs"),
("Olivia tells string joke 4.mp4","Bar / Drinking, Dad Jokes / Puns / Wordplay"),
("Pac tells ethnic joke 4.mp4","Race / Ethnic, Dark / Morbid"),
("Patrick F tells penguin joke.mp4","Animals, Dad Jokes / Puns / Wordplay"),
("Patrick tells a wife jokePG_topjokes.mp4","Relationship / Marriage / Dating, Bar / Drinking"),
("Patty tells penis joke.mp4","Dirty / Adult"),
("Paul tells a black joke.mp4","Race / Ethnic"),
("Paul tells black guy joke.mp4","Race / Ethnic"),
("Paul tells black joke.mp4","Race / Ethnic"),
("Paul tells penguin joke.mp4","Animals, Dad Jokes / Puns / Wordplay"),
("Paul tells priest joke.mp4","Religion, Dirty / Adult"),
("Pebble tells mummy joke wrong 3.mp4","Dad Jokes / Puns / Wordplay, Fails / Bombs"),
("Peter G tells blonde joke.mp4","Blonde"),
("Peter tells a jewish joke.mp4","Race / Ethnic, Dad Jokes / Puns / Wordplay"),
("Rabbi tells a rap jokePG.mp4","Dad Jokes / Puns / Wordplay"),
("Rachel tells a 3 wishes jokeR.mp4","Dirty / Adult, Race / Ethnic"),
("Randy K tells shitty will joke.mp4","Dirty / Adult"),
("Rasidio tells a sex jokeRtopjoke.mp4","Dirty / Adult"),
("Ready tells officer joke 4.mp4","Fails / Bombs"),
("Rebecca tells porcha joke.mp4","Dad Jokes / Puns / Wordplay"),
("Rebecca tells retard joke 5.mp4","Dark / Morbid, Self-Deprecating"),
("Rez animal aka _the yellow butt pirate_ 5#44D1.mp4","Race / Ethnic"),
("Rich V tells clown joke.mp4","Dark / Morbid, Food"),
("Rich tells a sex jokeR.mp4","Dirty / Adult"),
("Richie tells ethnic joke 4.mp4","Race / Ethnic, Animals, Dad Jokes / Puns / Wordplay"),
("Rick tells sex joke 5.mp4","Dirty / Adult, Relationship / Marriage / Dating"),
("Ricky tells a tissue joke.mp4","Dad Jokes / Puns / Wordplay"),
("Ro Jo and Lori tell an ethnic jokeR.mp4","Race / Ethnic"),
("Ro and Jo tell a lesbian jokeR.mp4","Dirty / Adult"),
("Ro and Jo tell an ethnic jokeR.mp4","Race / Ethnic, Dark / Morbid"),
("Rob tells a blonde jokeR.mp4","Blonde"),
("Rob tells a fat joke13.mp4","Dirty / Adult, Self-Deprecating"),
("Rob tells a hot dog jokeR.mp4","Dirty / Adult"),
("Rob tells an ethnic jokeR.mp4","Race / Ethnic, Religion, Dad Jokes / Puns / Wordplay"),
("Robby tells Mr Walsh 2 chinese jokes.mp4","Race / Ethnic, Dad Jokes / Puns / Wordplay"),
("Robert tells a blonde jokeR.mp4","Blonde, Dirty / Adult"),
("Robert tells dirty jokeR.mp4","Dad Jokes / Puns / Wordplay"),
("Robin tells amputee joke.mp4","Dark / Morbid, Doctor / Medical, Dad Jokes / Puns / Wordplay"),
("Roger tells a yo momma jokePG.mp4","Yo Mama"),
("Roman the Russian shoots youR - Copy.mp4","Race / Ethnic, Fails / Bombs"),
("Ron king tells bad joke 2 - Copy.mp4","Religion, Dirty / Adult"),
("Ron tells a Mike Tyson jokeR - Copy.mp4","Celebrity / Pop Culture, Dirty / Adult"),
("Ryan tells an einstein jokePG.mp4","Celebrity / Pop Culture, Dad Jokes / Puns / Wordplay"),
("Ryan tells another blonde joke.mp4","Blonde, Dirty / Adult"),
("Sam tells a cheater jokeR.mp4","Dirty / Adult, Relationship / Marriage / Dating, Religion"),
("Sam tells an ethnic jokeR.mp4","Race / Ethnic"),
("Samantha tells some jokesPG.mp4","Celebrity / Pop Culture, Kids Telling Jokes"),
("Santa tells a bad taste jokeR.mp4","Celebrity / Pop Culture, Dark / Morbid"),
("Santa tells a jokePG.mp4","Kids Telling Jokes, Dad Jokes / Puns / Wordplay"),
("Santiago tells cow joke.mp4","Animals, Dad Jokes / Puns / Wordplay"),
("Sarah tells drinking joke.mp4","Bar / Drinking, Dark / Morbid"),
("Sarah tells horse joke 3.mp4","Fails / Bombs"),
("Sarah tells lesbian joke 4.mp4","Dirty / Adult, Animals"),
("Sasha tells a witch joke .mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("Scott tells preacher joke 4.mp4","Religion, Dad Jokes / Puns / Wordplay"),
("Serena tells skeleton joke.mp4","Dad Jokes / Puns / Wordplay"),
("Seth Frankis.mp4","Animals, Fails / Bombs"),
("Seth tells dead baby joke.mp4","Dark / Morbid"),
("Seth tells three quick jokes.mp4","Bar / Drinking, Dirty / Adult, Dark / Morbid"),
("Shamus tells salad joke.mp4","Food, Dad Jokes / Puns / Wordplay"),
("Shana tells dirty joke.mp4","Dirty / Adult, Fails / Bombs"),
("Shaun tells a Priest joke.mp4","Religion, Dirty / Adult"),
("Shawn tells a baby seal jokePG.mp4","Animals, Bar / Drinking, Dad Jokes / Puns / Wordplay"),
("Shawn tells a woods jokeR.mp4","Dark / Morbid, Dirty / Adult"),
("Sheena tells a wise joke13.mp4","Religion, Dad Jokes / Puns / Wordplay"),
("Sheila tells a super bowl joke.mp4","Sports, Dad Jokes / Puns / Wordplay"),
("Sheldon tells a skeleton jokePG.mp4","Dad Jokes / Puns / Wordplay"),
("Sheldon tells a wife jokeR.mp4","Relationship / Marriage / Dating, Dirty / Adult"),
("Shoebia tells mickey mouse joke 4.mp4","Dirty / Adult, Relationship / Marriage / Dating, Celebrity / Pop Culture"),
("Simon tells a pillow jokePG.mp4","Dad Jokes / Puns / Wordplay"),
("Spencer and Mike tell an ethnic jokeR.mp4","Race / Ethnic"),
("Stacy tells an ethnic jokeR.mp4","Race / Ethnic"),
("Stav tells a blonde jokePG.mp4","Blonde"),
("Stephanie and Evelyn tell an ethnic joke13.mp4","Race / Ethnic"),
("Stephanie telling a jack joke.mp4","Dark / Morbid, Dirty / Adult"),
("Stephany tells polish joke.mp4","Race / Ethnic, Dad Jokes / Puns / Wordplay"),
("Stern fan almost tells a yo momma jokeR.mp4","Yo Mama, Fails / Bombs"),
("Stern fan does an angry pirate jokeR.mp4","Dirty / Adult, Dark / Morbid"),
("Stern fan tells an ethnic jokeR.mp4","Race / Ethnic"),
("Steve S tells a cash jokeR.mp4","Dirty / Adult"),
("Steve tells a Beethoven joke.mp4","Celebrity / Pop Culture, Fails / Bombs"),
("Steve tells a JFK jokeR.mp4","Celebrity / Pop Culture, Dark / Morbid"),
("Steve tells an ethnic joke13.mp4","Race / Ethnic, Dark / Morbid"),
("Steve tells gay joke 5.mp4","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("Steven tells a blonde joke.mp4","Blonde, Dirty / Adult"),
("Street guy tells a Christmas jokeR.mp4","Dirty / Adult"),
("Superfly tells ethnic joke 5.mp4","Race / Ethnic"),
("Superman 5.mp4","Fails / Bombs"),
("Susan tells man jokes 3.mp4","Dad Jokes / Puns / Wordplay"),
("Sylvio.mp4","Old Person Telling a Joke, Dad Jokes / Puns / Wordplay"),
("Tara tells an elephant joke13.mp4","Animals, Dirty / Adult"),
("Tasha, heather, molly tell poo joke.mp4","Dad Jokes / Puns / Wordplay, Animals"),
("Tatiana tells a chicken joke.mp4","Animals, Dad Jokes / Puns / Wordplay, Kids Telling Jokes"),
("Taylor and Courtney tell a Disney Japan joke13.mp4","Fails / Bombs"),
("Taylor tells an ethnic joke13.mp4","Race / Ethnic"),
("Ted tells a Hellen Keller jokePG.mp4","Dark / Morbid, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (1).mp4","Dad Jokes / Puns / Wordplay, Animals"),
("TellMeAJoke (10).mp4","Race / Ethnic, Food"),
("TellMeAJoke (100).mov","Race / Ethnic, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (101).mov","Political, Dirty / Adult"),
("TellMeAJoke (102).mov","Yo Mama"),
("TellMeAJoke (103).mov","Dirty / Adult, Dark / Morbid"),
("TellMeAJoke (104).mov","Race / Ethnic, Dirty / Adult"),
("TellMeAJoke (105).mov","Michael Jackson"),
("TellMeAJoke (106).mov","Race / Ethnic, Dirty / Adult"),
("TellMeAJoke (107).mov","Dad Jokes / Puns / Wordplay, Dirty / Adult"),
("TellMeAJoke (109).mov","Michael Jackson, Dark / Morbid"),
("TellMeAJoke (110).mov","Animals, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (111).mov","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (112).mov","Bar / Drinking, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (113).mov","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (115).mov","Animals, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (116).mov","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (117).mov","Dark / Morbid, Dirty / Adult"),
("TellMeAJoke (118).mov","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (119).mov","Dirty / Adult"),
("TellMeAJoke (12).mp4","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (120).mov","Yo Mama, Race / Ethnic"),
("TellMeAJoke (122).mov","Yo Mama, Food"),
("TellMeAJoke (123).mov","Blonde, Dirty / Adult"),
("TellMeAJoke (124).mov","Fails / Bombs"),
("TellMeAJoke (127).mov","Animals, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (128).mov","Yo Mama, Dark / Morbid"),
("TellMeAJoke (13).mp4","Blonde"),
("TellMeAJoke (130).mov","Blonde"),
("TellMeAJoke (131).mov","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (132).mov","Race / Ethnic"),
("TellMeAJoke (133).mov","Yo Mama, Fails / Bombs"),
("TellMeAJoke (135).mov","Dirty / Adult"),
("TellMeAJoke (136).mov","Dark / Morbid"),
("TellMeAJoke (139).mov","Michael Jackson"),
("TellMeAJoke (14).mp4","Yo Mama, Fails / Bombs"),
("TellMeAJoke (140).mov","Race / Ethnic, Dark / Morbid"),
("TellMeAJoke (142).mov","Celebrity / Pop Culture, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (143).mov","Dirty / Adult"),
("TellMeAJoke (144).mov","Doctor / Medical, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (145).mov","Dark / Morbid, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (148).mov","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (15).mp4","Animals, Bar / Drinking"),
("TellMeAJoke (150).mov","Dirty / Adult"),
("TellMeAJoke (154).mov","Dirty / Adult"),
("TellMeAJoke (155).mov","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (156).mov","Dark / Morbid, Food"),
("TellMeAJoke (158).mov","Race / Ethnic, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (159).mov","Animals, Dad Jokes / Puns / Wordplay, Dirty / Adult"),
("TellMeAJoke (16).mp4","Fails / Bombs"),
("TellMeAJoke (161).mov","Animals, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (162).mov","Political, Dirty / Adult"),
("TellMeAJoke (166).mov","Dirty / Adult"),
("TellMeAJoke (171).mov","Dark / Morbid, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (173).mov","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (175).mov","Doctor / Medical, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (176).mov","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (18).mp4","Dad Jokes / Puns / Wordplay, Food"),
("TellMeAJoke (180).mov","Blonde"),
("TellMeAJoke (183).mov","Dirty / Adult"),
("TellMeAJoke (184).mov","Sports, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (185).mov","Sports, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (187).mov","Fails / Bombs"),
("TellMeAJoke (188).mov","Race / Ethnic, Dark / Morbid"),
("TellMeAJoke (189).mov","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (19).mp4","Dirty / Adult, Dark / Morbid"),
("TellMeAJoke (190).mov","Race / Ethnic, Fails / Bombs"),
("TellMeAJoke (191).mov","Relationship / Marriage / Dating, Dark / Morbid"),
("TellMeAJoke (193).mov","Blonde, Dirty / Adult"),
("TellMeAJoke (196).mov","Relationship / Marriage / Dating, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (197).mov","Dirty / Adult"),
("TellMeAJoke (201).mov","Race / Ethnic, Dark / Morbid"),
("TellMeAJoke (202).mov","Dark / Morbid, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (205).mov","Dirty / Adult"),
("TellMeAJoke (206).mov","Knock Knock, Animals"),
("TellMeAJoke (207).mov","Dirty / Adult"),
("TellMeAJoke (211).mov","Celebrity / Pop Culture, Dark / Morbid"),
("TellMeAJoke (212).mov","Dirty / Adult, Lawyer"),
("TellMeAJoke (214).mov","Fails / Bombs"),
("TellMeAJoke (218).mov","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (22).mp4","Race / Ethnic, Sports"),
("TellMeAJoke (222).mov","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (223).mov","Race / Ethnic"),
("TellMeAJoke (224).mov","Yo Mama"),
("TellMeAJoke (225).mov","Fails / Bombs"),
("TellMeAJoke (227).mov","Race / Ethnic"),
("TellMeAJoke (23).mp4","Dark / Morbid, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (230).mov","Dirty / Adult"),
("TellMeAJoke (231).mov","Animals, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (232).mov","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (234).mov","Blonde"),
("TellMeAJoke (237).mov","Fails / Bombs"),
("TellMeAJoke (24).mp4","Fails / Bombs"),
("TellMeAJoke (240).mov","Fails / Bombs"),
("TellMeAJoke (242).mov","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (244).mov","Bar / Drinking, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (246).mov","Religion, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (247).mov","Animals, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (25).mp4","Blonde, Dirty / Adult"),
("TellMeAJoke (253).mov","Animals, Dirty / Adult, Food"),
("TellMeAJoke (254).mov","Dirty / Adult, Animals, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (255).mov","Animals, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (256).mov","Race / Ethnic, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (257).mov","Race / Ethnic, Dark / Morbid"),
("TellMeAJoke (259).mov","Dirty / Adult, Food"),
("TellMeAJoke (260).mov","Race / Ethnic, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (261).mov","Race / Ethnic, Dirty / Adult"),
("TellMeAJoke (262).mov","Race / Ethnic, Animals"),
("TellMeAJoke (264).mov","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (266).mov","Michael Jackson, Knock Knock"),
("TellMeAJoke (267).mov","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (268).mov","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (269).mov","Dirty / Adult, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (27).mp4","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (270).mov","Dad Jokes / Puns / Wordplay, Food"),
("TellMeAJoke (271).mov","Michael Jackson"),
("TellMeAJoke (273).mov","Fails / Bombs, Food"),
("TellMeAJoke (274).mov","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (276).mov","Fails / Bombs"),
("TellMeAJoke (277).mov","Self-Deprecating, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (278).mov","Bar / Drinking, Religion, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (28).mp4","Political, Celebrity / Pop Culture"),
("TellMeAJoke (280).mov","Dirty / Adult, Food"),
("TellMeAJoke (282).mov","Blonde"),
("TellMeAJoke (283).mov","Animals, Bar / Drinking"),
("TellMeAJoke (284).mov","Celebrity / Pop Culture, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (285).mov","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (286).mov","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (287).mov","Race / Ethnic, Political, Dirty / Adult"),
("TellMeAJoke (288).mov","Animals, Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (289).mov","Fails / Bombs"),
("TellMeAJoke (290).mov","Dark / Morbid, Dirty / Adult"),
("TellMeAJoke (291).mov","Michael Jackson"),
("TellMeAJoke (293).mov","Blonde"),
("TellMeAJoke (294).mov","Animals, Fails / Bombs"),
("TellMeAJoke (295).mov","Blonde"),
("TellMeAJoke (297).mov","Dirty / Adult"),
("TellMeAJoke (298).mov","Knock Knock"),
("TellMeAJoke (299).mov","Celebrity / Pop Culture, Fails / Bombs"),
("TellMeAJoke (300).mov","Dad Jokes / Puns / Wordplay"),
("TellMeAJoke (302).mov","Race / Ethnic, Dark / Morbid"),
("TellMeAJoke (304).mov","Dirty / Adult"),
("TellMeAJoke (305).mov","Dirty / Adult, Relationship / Marriage / Dating"),
("TellMeAJoke (306).mov","Bar / Drinking, Dad Jokes / Puns / Wordplay"),
]

def main():
    with open(THEMES_CSV, "w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["filename", "themes", "categorized_at"])
        for filename, themes in DATA:
            writer.writerow([filename, themes, NOW])
    print(f"Written {len(DATA)} rows to {THEMES_CSV}")

if __name__ == "__main__":
    main()
